// <auto-generated />
using BlazorArticleWeb.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace BlazorArticleWeb.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20250612114647_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.5");

            modelBuilder.Entity("BlazorArticleWeb.Models.ModelArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<int?>("_StyleId")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("_StyleId");

                    b.ToTable("Articles");
                });

            modelBuilder.Entity("BlazorArticleWeb.Models.ModelArticleStyle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Content")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("ArticleStyles");
                });

            modelBuilder.Entity("BlazorArticleWeb.Models.ModelArticle", b =>
                {
                    b.HasOne("BlazorArticleWeb.Models.ModelArticleStyle", "_Style")
                        .WithMany("_Articles")
                        .HasForeignKey("_StyleId");

                    b.Navigation("_Style");
                });

            modelBuilder.Entity("BlazorArticleWeb.Models.ModelArticleStyle", b =>
                {
                    b.Navigation("_Articles");
                });
#pragma warning restore 612, 618
        }
    }
}
